# Generated by Django 5.0.3 on 2024-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rectangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("color", models.CharField(max_length=7)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("size_x", models.IntegerField()),
                ("size_y", models.IntegerField()),
                ("rectangles", models.ManyToManyField(to="obrazki.rectangle")),
            ],
        ),
    ]
