# Generated by Django 5.0.3 on 2024-03-30 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obrazki", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="editors",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
