# Generated by Django 5.0.3 on 2024-04-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obrazki", "0002_picture_editors"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="picture",
            name="pub_date",
            field=models.DateTimeField(default=None, verbose_name="date published"),
        ),
    ]
